# Generated by Django 4.2.4 on 2023-08-28 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('document', models.CharField(max_length=100)),
                ('status', models.IntegerField(choices=[(1, 'Aprovada'), (2, 'Negada'), (3, 'Aguardando avaliação API'), (4, 'Aguardando avaliação humana')])),
            ],
        ),
        migrations.CreateModel(
            name='LoanRequestField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('field_type', models.IntegerField(choices=[(1, 'Integer'), (2, 'String'), (3, 'Datetime'), (4, 'Float')])),
                ('required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LoanRequestValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('field_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.loanrequestfield')),
                ('loan_request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.loanrequest')),
            ],
        ),
    ]
