# Generated by Django 4.2.4 on 2023-08-29 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanrequestvalue',
            old_name='loan_request_id',
            new_name='loan_request',
        ),
        migrations.RenameField(
            model_name='loanrequestvalue',
            old_name='field_id',
            new_name='loan_request_field',
        ),
        migrations.RemoveField(
            model_name='loanrequestfield',
            name='required',
        ),
    ]
